<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Default</name>
  <uuid>9f2514a4-2574-4d63-a0cb-13c465da283e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to true ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
