<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Validation</name>
  <uuid>355d8976-f57e-4055-a690-ef16ac013ffe</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 
	any of the following conditions is true : 
	- age is less than 18
    - income is less than 5000
then
set decision to false ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
